### ISSUE TITLE
Update to Readme

### ISSUE THREAD

**Issue by samhilmw** [Auto-DL/Generator#130]
## Bug Report

Add example directory structure in Reademe point 5

### Current
Place data in the ./DLMML/data directory.

### Proposed
Place data in the ./DLMML/data directory.
Example for Cats vs Dogs classification
./DMML/data
&emsp;&emsp;&emsp;&emsp; |-train
&emsp;&emsp;&emsp;&emsp; | &emsp; |-cats
&emsp;&emsp;&emsp;&emsp; | &emsp;  '-dogs
&emsp;&emsp;&emsp;&emsp; |-test
&emsp;&emsp;&emsp;&emsp; &emsp;&nbsp; |-cats
&emsp;&emsp;&emsp;&emsp; &emsp; &nbsp; '-dogs

**Comment by ADI10HERO** [comment]
Intuitive, will do it now
