### ISSUE TITLE
Error while executing " git submodule update " command. 

### ISSUE THREAD

**Issue by Halix267** [Auto-DL/Generator#20]
![asdasd](https://user-images.githubusercontent.com/63572018/93716537-feae0780-fb8d-11ea-94c1-550c71fd9cd6.JPG)

**Comment by Halix267** [comment]
Plz help

**Comment by ADI10HERO** [comment]
Firstly, thank you for letting us know about the issue.

I have fixed the bug. 
Please pull the latest version from the default branch.
Let me know if the problem persists.

Thanks,
Adi

**Comment by Halix267** [comment]
Thank you @ADI10HERO .
Now the command is working :)

**Comment by ADI10HERO** [comment]
Cool...
So I am closing the issue, feel free to reopen in case you face it again
