### ISSUE TITLE
Add "Join our Slack Community" badge to readme 

### ISSUE THREAD

**Issue by ADI10HERO** [Auto-DL/Generator#28]
Please find how it is done ideally in popular open source orgs, "badge" is not a compulsion, just somehow (correct way) link to the slack channel should be there.

**Comment by jscastanos** [comment]
Hi, I'd like to work on this.

**Comment by dumbcheese** [comment]
Hey, I can't seem to find the your slack channel, could you just post it here and I can add that badge :)

**Comment by ADI10HERO** [comment]
@dumbcheese  https://join.slack.com/t/autodl/shared_invite/zt-ig3dwj68-4U_lfyQeb5LZueKZbNyDXw

👍
