### ISSUE TITLE
Payment gateway integration needed - Razorpay

### ISSUE THREAD

**Issue by rj8228** [Auto-DL/Generator#375]
## Feature Request

Is your feature request related to an existing [Issue](https://www.github.com/Auto-DL/Generator/issues) or a new implementation?

### Feature Description

Payment integration needed for NextJS, we'll use razorpay.
We expect Both frontend and backend for this PR.
Place the Donate/Support Us button on the bottom left of the UI, in navbar

### Possible Solution

Starting point - https://razorpay.com/docs/payment-gateway/
### Additional context

While pushing the code, remove all the API keys and replace it with API_KEY or according names.

**Comment by priyanshm07** [comment]
Hello, @rajraj889 I have previously worked with Razorpay Integrations.
Could You please it to me? 
It would be great working on this.

**Comment by ADI10HERO** [comment]
Hey @priyanshm07, amazing, as this is a big feature, I'd suggest the following:
- Join the Auto-DL slack for easy communication (#frontend would be the ideal place to start)
- Please let us know roughly when do you plan to add the feature (Note: It is not a hard deadline, just changes mindset :))
- Have you set up Auto-DL locally? If not, please visit our [docs page](https://docs.auto-dl.tech/en/latest/)

**Comment by priyanshm07** [comment]
Thanks, @ADI10HERO For assigning It to me.
Setting Auto-Dl locally, and starting working on it.

**Comment by priyanshm07** [comment]
@ADI10HERO, I have started working on it.
Will soon be sharing the updates.
