### ISSUE TITLE
Contributing.md Empty file

### ISSUE THREAD

**Issue by dumbcoder7** [Auto-DL/Generator#47]
Wanted to start contributing to the repository. The README file says read the contributing guidelines before actually contributing, but guess what.

Consider adding contents to the file.

**Comment by ADI10HERO** [comment]
Thank you so much for the initiative.

Yes, we know all the guides and documentation are empty files. They are a little down on our priority list as of now. We'll surely consider reprioritizing. 

Would love some help in that area.

Thanks,
Adi

**Comment by dumbcoder7** [comment]
Cool, I'll see how I can help with that file.

**Comment by dumbcoder7** [comment]
Fixed with PR #50
