### ISSUE TITLE
Rearrange README

### ISSUE THREAD

**Issue by adityaraute** [Auto-DL/Generator#91]
## Feature Request

Is your feature request related to an existing [Issue](https://www.github.com/Auto-DL/Generator/issues) or a new implementation?
*NO*

### Feature Description

The *Demo* tab in the [README](https://github.com/Auto-DL/Generator/blob/v1-alpha/README.md) should be placed above the *How To Run* section.

### Possible Solution

Create an up-to-date DEMO gif file, and place it above the *How To Run* section.

### Additional context

This enables the user to see the product in working and motivates them to use the deployed version themselves. If they wish to run the project locally, they can always search. But that might not be everybody's objective.

**Comment by ADI10HERO** [comment]
@gayatribelapurkar 

The new GIF can be made from the Video [here](https://www.youtube.com/watch?v=6uEt88vQxQU) 
Also please upload the gif to our OSS Drive Media Section
